'use strict';

/**
 * WINE AI KOS - Extraction Field Policies (Step 3A Refined)
 *
 * Comprehensive field policy definitions detailing constraints, units, cardinality, and evidence policies.
 */

const EXTRACTION_FIELD_POLICIES = Object.freeze({
    'wine.name': {
        fieldPath: 'wine.name',
        entityType: 'wine',
        valueType: 'string',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'heading_context', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.8,
        automaticApproval: false,
        conflictPolicy: 'flag',
        maxLength: 250,
    },
    'wine.vintageYear': {
        fieldPath: 'wine.vintageYear',
        entityType: 'wine',
        valueType: 'year',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.85,
        automaticApproval: false,
        conflictPolicy: 'flag',
        minimum: 1800,
        maximum: 2030,
    },
    'wine.alcoholPercent': {
        fieldPath: 'wine.alcoholPercent',
        entityType: 'wine',
        valueType: 'decimal',
        unit: 'percent_abv',
        allowedUnits: ['percent_abv'],
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.85,
        automaticApproval: false,
        conflictPolicy: 'flag',
        minimum: 0.0,
        maximum: 30.0,
    },
    'wine.volumeMl': {
        fieldPath: 'wine.volumeMl',
        entityType: 'wine',
        valueType: 'integer',
        unit: 'ml',
        allowedUnits: ['ml'],
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.85,
        automaticApproval: false,
        conflictPolicy: 'flag',
        minimum: 50,
        maximum: 10000,
    },
    'wine.price': {
        fieldPath: 'wine.price',
        entityType: 'wine',
        valueType: 'money',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.8,
        automaticApproval: false,
        conflictPolicy: 'flag',
    },
    'winery.brandName': {
        fieldPath: 'winery.brandName',
        entityType: 'winery',
        valueType: 'string',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'heading_context', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.8,
        automaticApproval: false,
        conflictPolicy: 'flag',
        maxLength: 250,
    },
    'winery.foundingYear': {
        fieldPath: 'winery.foundingYear',
        entityType: 'winery',
        valueType: 'year',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'table_cell', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.85,
        automaticApproval: false,
        conflictPolicy: 'flag',
        minimum: 1500,
        maximum: 2030,
    },
    'winery.website': {
        fieldPath: 'winery.website',
        entityType: 'winery',
        valueType: 'url',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.9,
        automaticApproval: false,
        conflictPolicy: 'flag',
    },
    'winery.email': {
        fieldPath: 'winery.email',
        entityType: 'winery',
        valueType: 'email',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.9,
        automaticApproval: false,
        conflictPolicy: 'flag',
    },
    'winery.phone': {
        fieldPath: 'winery.phone',
        entityType: 'winery',
        valueType: 'phone',
        cardinality: 'single',
        evidenceRequired: true,
        allowedEvidenceTypes: ['direct_quote', 'label_value_pair'],
        languagePolicy: 'any',
        minimumConfidence: 0.85,
        automaticApproval: false,
        conflictPolicy: 'flag',
    },
});

function getFieldPolicy(fieldPath) {
    if (!fieldPath || typeof fieldPath !== 'string') return null;
    return EXTRACTION_FIELD_POLICIES[fieldPath] || null;
}

module.exports = {
    EXTRACTION_FIELD_POLICIES,
    getFieldPolicy,
};
